export const DRINKING_QUOTES = [
  "I don’t have a drinking problem… I drink, I get drunk, I fall down. No problem. 🍺😌",
  "Alcohol may not solve your problems, but neither will water. 🍻🤷‍♂️",
  "I cook with wine. Sometimes I even add it to the food. 🍷👨‍🍳",
  "I’m not drunk, I’m just speaking in cursive. 🥴✍️",
  "Beer is proof that God loves us and wants us to be happy. 🍺😇",
  "Drink responsibly… don’t spill it. 🍻😂",
  "My favorite exercise is lifting a glass and putting it to my lips. 💪🍷",
  "Alcohol: because no great story ever started with a salad. 🥗❌🍺",
  "I need a drink… or five. 🥃🥃🥃🥃🥃",
  "I make pour decisions. 🍷😏",
  "I’m on a whiskey diet. I’ve lost three days already. 🥃📆",
  "Life is too short to drink bad beer. 🍺👌",
  "I don’t get drunk, I get awesome. 😎🍻",
  "Beer before liquor, never been sicker. Liquor before beer… bold move. 🤔🍺🥃",
  "Save water. Drink beer. 🌍🍺",
  "I only drink on days that end with ‘y’. 📅🍻",
  "Drinking alone is called being a connoisseur. 🧐🍷",
  "I’m not an alcoholic — alcoholics go to meetings. 🍺😅",
  "A balanced diet is a beer in each hand. ⚖️🍺🍺",
  "You can’t buy happiness, but you can buy beer, and that’s close enough. 🍻😁",
  "I have mixed drinks about feelings. 🍹💭",
  "When life gives you lemons, add vodka. 🍋➕🥃",
  "I drink to make other people more interesting. 👀🍷",
  "I like my beer like I like my jokes — dark and inappropriate. 🍺😈",
  "I’m not tipsy, the floor is drunk. 🥴🪑",
  "Beer: because adulting is hard. 😩🍺",
  "I came. I saw. I made it awkward while drunk. 🍻😬",
  "Drinking buddies are cheaper than therapy. 🛋️🍺",
  "Wine improves with age. I improve with wine. 🍷✨",
  "Trust me — you can dance. 🍻💃",
  "This game ended… but the drinks didn’t. 🕹️🍺",
  "One drink is too many, ten is not enough. 😵🍻",
  "I’m not drunk, I’m just buffering. ⏳🥴",
  "Beer is my spirit animal. 🐻🍺",
  "I have a degree in mixology… from my couch. 🎓🍹",
  "Drinking is just borrowing happiness from tomorrow. 😄➡️😵",
  "If at first you don’t succeed, then pour another drink. 🍸😌",
  "I don’t chase dreams, I chase drinks. 🏃‍♂️🍻",
  "Game over. Time to level up the drinks. 🎮🍺",
];
