INSERT INTO "Parms" ("type", "name", "value", "createdAt")
SELECT 'EDITIONS', '😜 On a date edtion', 10, NOW()
WHERE NOT EXISTS (
  SELECT 1
  FROM "Parms"
  WHERE "type" = 'EDITIONS'
    AND "value" = 10
);

INSERT INTO "Question" ("text", "gameId", "edition", "createdAt", "updatedAt")
SELECT prompts."text", g."id", edition."value", NOW(), NOW()
FROM (
  VALUES
    ('What was your first impression of me?', 10),
    ('What part of my vibe stands out most tonight?', 10),
    ('What do you think I''m better at than I realize?', 10),
    ('What''s something small I''ve done tonight that you found attractive?', 10),
    ('What do you think I was nervous about before this date?', 10),
    ('What would you guess is my biggest dating green flag?', 10),
    ('What would you guess is my biggest dating red flag?', 10),
    ('What kind of person do you think usually falls for me?', 10),
    ('What kind of person do you think I usually fall for?', 10),
    ('What song would you use to describe this date so far?', 10),
    ('What''s the most charming thing you''ve noticed about me tonight?', 10),
    ('What''s one thing you still want to know about me before the night ends?', 10),
    ('What''s something you hope I notice about you?', 10),
    ('If you had to compliment me without mentioning looks, what would you say?', 10),
    ('What do you think is secretly very cute about me?', 10),
    ('What energy do I give off: danger, comfort, chaos, or romance?', 10),
    ('What kind of date do I seem best suited for: fancy, spontaneous, cozy, or wild?', 10),
    ('What''s one thing I could say tonight that would instantly win you over?', 10),
    ('What would your friends assume about me if they saw us together right now?', 10),
    ('What do you think my flirting style is?', 10),
    ('What''s the most memorable date you''ve ever had?', 10),
    ('What''s the worst date you''ve ever been on?', 10),
    ('Have you ever liked someone immediately? What happened?', 10),
    ('What''s something you learned from a bad relationship?', 10),
    ('What''s something you learned from a great relationship?', 10),
    ('What''s your biggest dating ick?', 10),
    ('What''s a small thing someone can do that makes you melt a little?', 10),
    ('What''s something people misunderstand about how you love?', 10),
    ('Have you ever fumbled a chance with someone you really liked?', 10),
    ('What''s the boldest move you''ve made on a date?', 10),
    ('What''s your favorite kind of kiss?', 10),
    ('What makes someone instantly more attractive to you?', 10),
    ('What kind of eye contact feels too intense in a good way?', 10),
    ('What kind of touch gives you butterflies?', 10),
    ('What outfit on someone gets your attention fast?', 10),
    ('What''s more attractive: confidence, humor, kindness, or mystery?', 10),
    ('What''s a non-physical thing that turns you on?', 10),
    ('What''s something subtle someone can do that feels very seductive?', 10),
    ('What kind of compliment actually gets to you?', 10),
    ('When do you usually realize you''re attracted to someone?', 10),
    ('What''s your biggest green flag in dating?', 10),
    ('What behavior makes you feel safe with someone?', 10),
    ('What''s something that earns your trust quickly?', 10),
    ('What''s something that makes you pull back emotionally?', 10),
    ('What does consistency look like to you in dating?', 10),
    ('What kind of communication style works best for you?', 10),
    ('What''s something you need but don''t always ask for?', 10),
    ('How do you act when you really like someone?', 10),
    ('How can someone tell you''re losing interest?', 10),
    ('What makes a date feel genuinely successful to you?', 10),
    ('What kind of partner do you think suits you best?', 10),
    ('What kind of dates make you feel most alive?', 10),
    ('What''s your ideal way to spend an entire day with someone you like?', 10),
    ('Are you more of a slow-burn or instant-spark type?', 10),
    ('What matters more to you: chemistry or compatibility?', 10),
    ('What does romance look like in your world?', 10),
    ('What''s something surprisingly important to you in a partner?', 10),
    ('What''s your love language when you really care about someone?', 10),
    ('What''s the difference between liking someone and really wanting them?', 10),
    ('What kind of relationship would excite you right now?', 10),
    ('What''s something innocent that feels very intimate to you?', 10),
    ('Have you ever had a "we should not be this into each other this fast" connection?', 10),
    ('What part of a first date usually tells you the most?', 10),
    ('What makes you want to see someone again?', 10),
    ('What''s one question you wish more dates asked you?', 10),
    ('What kind of goodbye at the end of a date do you like best?', 10),
    ('What''s a tiny romantic gesture that works on you every time?', 10),
    ('Have you ever been kissed at the perfect moment?', 10),
    ('What kind of tension do you secretly enjoy?', 10),
    ('What''s something about dating that''s more vulnerable than people admit?', 10),
    ('What do you think I''m like when I really like someone?', 10),
    ('What do you think I''m hiding behind my confidence tonight?', 10),
    ('What kind of person do you think could break my heart?', 10),
    ('What kind of person do you think could calm me down instantly?', 10),
    ('What do you think I want from dating, even if I haven''t said it?', 10),
    ('What trait of mine do you think would make someone obsessed?', 10),
    ('What do you think my toxic dating habit might be?', 10),
    ('What do you think my sweetest relationship habit might be?', 10),
    ('If you had to guess, what kind of affection do I give best?', 10),
    ('What kind of compliment do you think I most want to hear?', 10),
    ('What''s something you want more of in your dating life?', 10),
    ('What''s something you want less of in your dating life?', 10),
    ('What''s a risk you wish you took sooner in love?', 10),
    ('What kind of connection are you craving lately?', 10),
    ('What makes you feel chosen by someone?', 10),
    ('What''s one wall you still keep up when dating?', 10),
    ('What makes you finally let that wall down?', 10),
    ('What''s something you''ve been too shy to admit on a date before?', 10),
    ('What do you wish people understood about your heart?', 10),
    ('What does emotional intimacy feel like to you?', 10),
    ('If we had a second date, what should it absolutely include?', 10),
    ('What do you think would make this date unforgettable?', 10),
    ('What moment tonight has had the best energy so far?', 10),
    ('What would surprise me most about your romantic side?', 10),
    ('What would your ideal late-night conversation with someone you like sound like?', 10),
    ('What is your most dangerous flirting habit?', 10),
    ('What''s one thing you''d want me to remember about you tomorrow?', 10),
    ('What''s one thing you hope I felt from you tonight?', 10),
    ('What would make you want to kiss someone before the date ends?', 10),
    ('Based on tonight so far, would you want another date and why?', 10),
    ('What''s your cutest bad habit when you like someone?', 10),
    ('What''s your favorite kind of first-date chaos?', 10),
    ('What drink order feels the flirtiest to you?', 10),
    ('What''s a harmless lie people tell on dates all the time?', 10),
    ('What''s one thing you fake confidence about when dating?', 10),
    ('What''s something silly that instantly breaks the tension for you?', 10),
    ('What''s your funniest dating fail?', 10),
    ('What''s something that would make this date way more iconic?', 10),
    ('Have you ever practiced something before a date?', 10),
    ('What''s the cheesiest thing that still works on you?', 10),
    ('What''s a compliment that will always make you smile?', 10),
    ('What''s one thing people do on dates that is secretly adorable?', 10),
    ('What''s a tiny sign that tells you someone is into you?', 10),
    ('What''s a question that instantly makes a date more fun?', 10),
    ('What''s a random talent that becomes attractive on a date?', 10),
    ('What''s a snack you would judge me for ordering but still steal?', 10),
    ('What''s your best flirt line that sounds accidental?', 10),
    ('What''s something awkward you find weirdly charming?', 10),
    ('What''s your ideal excuse to extend a date by one more hour?', 10),
    ('What''s a text after a date that would make you grin immediately?', 10),
    ('What''s the most unserious reason you''ve liked someone?', 10),
    ('What''s a soft launch clue that someone has your attention?', 10),
    ('What''s something you secretly love when a date notices?', 10),
    ('What''s your favorite kind of teasing?', 10),
    ('What''s something goofy you hope a partner would do with you?', 10),
    ('What''s the quickest way to make you laugh for real?', 10),
    ('What''s a random thing that gives you butterflies every time?', 10),
    ('What''s your favorite excuse to accidentally touch someone you like?', 10),
    ('What''s a very innocent thing that feels flirty to you?', 10),
    ('What''s your favorite kind of date-night outfit on yourself?', 10),
    ('What''s one thing you always notice about someone''s smile?', 10),
    ('What''s the best spontaneous date idea you can think of right now?', 10),
    ('What''s your favorite way to be hyped up by someone you like?', 10),
    ('What''s something playful you wish more people did while flirting?', 10),
    ('What''s a totally harmless thing that makes you blush?', 10),
    ('What''s your favorite excuse to stay up too late with someone?', 10),
    ('What''s one thing you would absolutely roast your date for, lovingly?', 10),
    ('What''s your favorite kind of late-night energy?', 10),
    ('What''s the cutest thing someone can remember about you?', 10),
    ('What''s your favorite kind of accidental chemistry?', 10),
    ('What''s something you would definitely post-close-friends but not public?', 10),
    ('What''s the most flirtatious food to share?', 10),
    ('What''s the best part of building tension with someone?', 10),
    ('What''s a bold move you admire even if it''s a little reckless?', 10),
    ('What''s the most playful way someone could ask for a second date?', 10),
    ('What''s a harmless competitive game that gets you flirty fast?', 10),
    ('What''s your ideal after-date song on the ride home?', 10),
    ('What''s a look across the table that would absolutely get you?', 10),
    ('What''s your favorite thing to hear from someone who''s into you?', 10),
    ('What''s a moment on a date where you usually decide whether the spark is real?', 10),
    ('What''s something you''d only reveal if the date was going really well?', 10),
    ('What''s one sweet thing you hope people notice beneath your flirting?', 10),
    ('What makes you feel emotionally relaxed with someone new?', 10),
    ('What kind of honesty feels romantic instead of scary to you?', 10),
    ('What''s a value you really want shared in a relationship?', 10),
    ('What kind of support makes you feel deeply cared for?', 10),
    ('What''s one lesson your love life taught you that you''re grateful for?', 10),
    ('What kind of apology lands best with you?', 10),
    ('What''s something you want your future partner to understand about your pace?', 10),
    ('What makes you feel respected while dating?', 10),
    ('What kind of affection feels most sincere to you?', 10),
    ('What''s one thing you need in order to feel emotionally safe?', 10),
    ('What''s something you wish more people asked before assuming?', 10),
    ('What kind of effort means the most to you?', 10),
    ('What''s a sign of emotional maturity that immediately impresses you?', 10),
    ('What''s something you want to do better in your next relationship?', 10),
    ('What''s a boundary that actually improved your dating life?', 10),
    ('What kind of consistency feels most attractive to you?', 10),
    ('What''s something you''ve learned about choosing better?', 10),
    ('What makes you feel calm instead of confused in romance?', 10),
    ('What kind of reassurance do you appreciate most?', 10),
    ('What''s one thing that helps you trust someone over time?', 10),
    ('What''s a trait you admire in couples who seem genuinely solid?', 10),
    ('What kind of emotional check-in feels comforting to you?', 10),
    ('What''s one thing people often overlook that matters a lot to you?', 10),
    ('What kind of conversations make you feel closest to someone?', 10),
    ('What''s a simple act of care that means a lot to you?', 10),
    ('What makes you feel like a relationship has real potential?', 10),
    ('What kind of peace do you want love to bring into your life?', 10),
    ('What''s a relationship habit you would love to build with the right person?', 10),
    ('What does being emotionally available look like to you?', 10),
    ('What kind of future feels exciting to imagine with someone?', 10),
    ('What''s one thing you hope love feels like next time?', 10),
    ('What''s one insecurity that sometimes follows you into dating?', 10),
    ('What''s something you want to be better understood for in relationships?', 10),
    ('What''s a fear you have when you start liking someone?', 10),
    ('What kind of mixed signal throws you off the most?', 10),
    ('What''s something you still overthink after a date?', 10),
    ('What''s a soft spot that gets activated when you''re into someone?', 10),
    ('What''s something you need time to open up about?', 10),
    ('What makes you pull away even when you like someone?', 10),
    ('What''s a difficult truth you''ve learned about your dating patterns?', 10),
    ('What''s one thing that can make you doubt yourself fast in romance?', 10),
    ('What''s a part of you that''s hard to show early on?', 10),
    ('What''s one thing you''re trying not to repeat from the past?', 10),
    ('What kind of disappointment hits hardest for you in dating?', 10),
    ('What makes you feel misunderstood when you''re trying your best?', 10),
    ('What''s one thing you wish you could say more easily when dating?', 10),
    ('What''s a moment when you realized you were settling before?', 10),
    ('What kind of connection makes you most emotionally vulnerable?', 10),
    ('What''s something you''re still learning about your needs?', 10),
    ('What makes you feel deeply seen by the right person?', 10),
    ('What''s one thing you want to unlearn about love?', 10),
    ('What kind of kindness always reaches you?', 10),
    ('What''s something you crave that you don''t always know how to ask for?', 10),
    ('What''s a trait in yourself you hope the right person appreciates?', 10),
    ('What''s one thing you''ve healed enough to recognize quickly now?', 10),
    ('What''s a pattern you''re trying to replace with something healthier?', 10),
    ('What would make you feel chosen in a really genuine way?', 10),
    ('What''s something you need from yourself before the right relationship works?', 10),
    ('What''s one thing you''re proud of in how you love now?', 10),
    ('What''s one thing that makes you feel ridiculously attractive?', 10),
    ('What kind of kiss should absolutely come with dramatic eye contact?', 10),
    ('What''s one fantasy date location that would definitely raise the heat?', 10),
    ('What''s the boldest compliment you like receiving?', 10),
    ('What kind of text from someone you like feels dangerous in the best way?', 10),
    ('What''s your favorite kind of tension before a first kiss?', 10),
    ('What''s a look that says more than words ever could?', 10),
    ('What''s the flirtiest thing someone can whisper to you?', 10),
    ('What kind of confidence is almost unfairly attractive?', 10),
    ('What''s the most electric part of a good date?', 10),
    ('What''s something that makes you want to sit a little closer?', 10),
    ('What''s a playful move that instantly upgrades the chemistry?', 10),
    ('What''s your favorite kind of build-up?', 10),
    ('What''s a compliment that would definitely stay in your head all night?', 10),
    ('What''s one thing someone could do that would make you want them to kiss you?', 10),
    ('What kind of voice immediately gets your attention?', 10),
    ('What''s your favorite kind of after-dark flirting?', 10),
    ('What''s something subtle that feels way too hot?', 10),
    ('What''s a situation where you know you''d fold immediately?', 10),
    ('What''s a tiny detail about someone that can drive you a little crazy?', 10),
    ('What''s more intense to you: lingering eye contact or a low voice?', 10),
    ('What''s one thing you should probably not find hot but do?', 10),
    ('What kind of banter makes the chemistry obvious?', 10),
    ('What''s the most flirtatious kind of goodbye?', 10),
    ('What''s a kind of confidence that belongs in a movie scene?', 10),
    ('What''s your favorite kind of tension across a table?', 10),
    ('What''s something you would call a red flag if it weren''t so attractive?', 10),
    ('What''s one thing that makes someone dangerously charming?', 10),
    ('What''s your favorite kind of almost-touch?', 10),
    ('What''s the boldest way someone could ask you to stay a little longer?', 10),
    ('What kind of compliment sounds innocent but definitely is not?', 10),
    ('What''s one thing that makes you want to flirt harder?', 10),
    ('What''s your favorite kind of teasing when the chemistry is mutual?', 10),
    ('What''s a move that says "I know exactly what I''m doing" in a hot way?', 10),
    ('What''s one thing someone could say tonight that would have you replaying it later?', 10),
    ('What kind of confidence do you secretly find irresistible?', 10),
    ('What''s a very simple touch that feels way more intimate than it should?', 10),
    ('What''s one thing someone can do with their eyes that ruins your composure?', 10),
    ('What''s your favorite kind of "we both know what this is" moment?', 10),
    ('What''s something you pretend not to notice on purpose when you''re flirting?', 10),
    ('What kind of energy makes you instantly bolder?', 10),
    ('What''s the kind of chemistry that makes time feel fake?', 10),
    ('What''s a kind of tension that should come with a warning label?', 10),
    ('What''s one thing you would love to hear right before a kiss?', 10),
    ('What''s a move that belongs in a very good second date?', 10),
    ('What kind of smile feels a little unfairly powerful?', 10),
    ('What''s the most seductive thing someone can do without touching you?', 10),
    ('What''s your favorite kind of "accidental" flirting?', 10),
    ('What kind of date setting makes chemistry hit twice as hard?', 10),
    ('What''s a detail about someone that can become wildly distracting?', 10),
    ('What''s one thing that makes a kiss feel unforgettable?', 10),
    ('What''s something playful that can turn very flirty very fast?', 10),
    ('What''s your favorite kind of tension to break?', 10),
    ('What''s a line that would absolutely work on you if delivered right?', 10),
    ('What kind of person makes you want to be more daring?', 10),
    ('What''s the flirtiest kind of silence?', 10),
    ('What''s one thing that makes you feel like you''re in trouble in a fun way?', 10),
    ('What''s something about attraction you wish people admitted more honestly?', 10),
    ('What''s the most obvious sign you''re trying not to flirt too much?', 10),
    ('What kind of date moment usually becomes the turning point?', 10),
    ('What''s one thing you like that feels innocent in public but not in private?', 10),
    ('What''s your favorite kind of spark to feel with someone?', 10),
    ('What''s one thing you hope a partner would never stop doing for you?', 10),
    ('What kind of intimacy feels more meaningful to you than it looks from the outside?', 10),
    ('What''s something you want to be brave enough to ask for in love?', 10),
    ('What kind of relationship dynamic feels healthiest to you now?', 10),
    ('What''s a simple routine you''d love to share with the right person?', 10),
    ('What kind of care makes you feel deeply held?', 10),
    ('What''s one thing about your heart that gets stronger with the right person?', 10),
    ('What kind of home energy would you want with a partner?', 10),
    ('What''s something you''d love to experience slowly with someone?', 10),
    ('What kind of encouragement means the most to you from someone you love?', 10),
    ('What''s one thing you hope feels easy in your next relationship?', 10),
    ('What kind of closeness feels like peace to you?', 10),
    ('What''s a romantic habit that you think helps love last?', 10),
    ('What kind of trust would you love to build with someone over time?', 10),
    ('What''s one dream that would be sweeter to chase with the right person?', 10),
    ('What kind of support helps you bloom instead of just cope?', 10),
    ('What''s one thing you hope your future relationship protects instead of tests?', 10),
    ('What kind of love story feels believable to you now?', 10),
    ('What''s something you want more softness around in your love life?', 10),
    ('What kind of effort do you think keeps attraction alive long-term?', 10),
    ('What''s a way you want to feel adored beyond just being desired?', 10),
    ('What kind of growth would you love to experience with a partner?', 10),
    ('What''s one thing that would make commitment feel exciting instead of scary?', 10),
    ('What kind of joy do you want love to add to your daily life?', 10),
    ('What''s one version of romance you want more of as you get older?', 10),
    ('What kind of emotional honesty feels most intimate to you?', 10),
    ('What''s one thing you want your future partner to feel safe bringing to you?', 10)
) AS prompts("text", "edition")
JOIN "Game" g ON g."code" = 'truth-or-drink'
JOIN "Parms" edition
  ON edition."type" = 'EDITIONS'
 AND edition."value" = 10
WHERE NOT EXISTS (
  SELECT 1
  FROM "Question" q
  WHERE q."gameId" = g."id"
    AND q."edition" = edition."value"
    AND q."text" = prompts."text"
);
