INSERT INTO "Game" ("code", "name", "description", "published", "createdAt", "updatedAt")
SELECT
  'you-laugh-you-drink',
  'You Laugh, You Drink',
  'Face-off party game where one player attacks with a ridiculous prompt and the target tries not to laugh.',
  true,
  NOW(),
  NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM "Game" WHERE "code" = 'you-laugh-you-drink'
);

INSERT INTO "Question" ("text", "gameId", "createdAt", "updatedAt")
SELECT prompts."text", g."id", NOW(), NOW()
FROM (
  VALUES
    ('Explain how to make toast like it is a dangerous black-market operation.'),
    ('Ask your Target for the Wi-Fi password like a dramatic soap-opera villain.'),
    ('Pretend you are a motivational speaker trying to inspire one lonely french fry.'),
    ('Introduce your elbow as if it is the newest celebrity in the room.'),
    ('Try to flirt using only pirate energy and very bad confidence.'),
    ('Describe a banana like it is the final boss in an action movie.'),
    ('Apologize to a chair for betraying its trust.'),
    ('Act like a museum tour guide showing off an invisible sock.'),
    ('Tell your Target a bedtime story in the voice of an exhausted referee.'),
    ('Order a pizza as if you are negotiating world peace.'),
    ('Pretend your shoe is giving you terrible life advice.'),
    ('Give a weather report about your Target''s hairstyle.'),
    ('Sell an invisible goat like you are on late-night TV.'),
    ('Explain how to boil water as if nobody has survived it before.'),
    ('React to a paper clip like it just insulted your family.'),
    ('Perform a luxury perfume ad for plain tap water.'),
    ('Describe your Target as a rejected superhero sidekick.'),
    ('Beg a potato to believe in itself.'),
    ('Try to sound romantic while discussing laundry detergent.'),
    ('Announce snack time like a king addressing the kingdom.'),
    ('Pretend you are a detective interrogating a suspicious spoon.'),
    ('Give a TED Talk about why naps should be an Olympic sport.'),
    ('Act like a flight attendant on a dragon.'),
    ('Complain about traffic while sitting perfectly still.'),
    ('Teach your Target how to be mysterious while holding imaginary groceries.'),
    ('Introduce yourself like a wrestler named Microwave Thunder.'),
    ('Pretend your phone just broke up with you in public.'),
    ('Explain taxes to a goldfish with full confidence.'),
    ('Narrate your own slow-motion entrance into a room full of sandwiches.'),
    ('Act like a tiny angry chef reviewing cereal.'),
    ('Beg your Target to join your made-up cult of fancy socks.'),
    ('Describe a toothbrush like it belongs in a heist movie.'),
    ('Pretend you are a horse with a podcast.'),
    ('Ask for directions as if you are speaking to an ancient wizard.'),
    ('Announce that you have discovered a new emotion called crunchy sadness.'),
    ('Pitch a reality show about dramatic houseplants.'),
    ('Explain the moon to someone who absolutely does not care.'),
    ('Act like your Target just won an award for average behavior.'),
    ('Describe a handshake like it is forbidden magic.'),
    ('Try to intimidate your Target using only dad-energy.'),
    ('Pretend you are a lawyer defending a very guilty pancake.'),
    ('Make a serious public statement about disappearing leftovers.'),
    ('Give a sports commentary for someone opening a bag of chips.'),
    ('Act like your invisible pet llama keeps interrupting you.'),
    ('Explain your weekend plans like a supervillain monologue.'),
    ('Pretend a grape has challenged you to combat.'),
    ('Perform a heartfelt apology to the concept of Monday.'),
    ('Describe your Target''s laugh like it has its own fan club.'),
    ('Try to recruit your Target into the Department of Silly Walks and Accounting.'),
    ('Act like you are too emotionally invested in a coin toss.'),
    ('Explain a sandwich to an alien who keeps asking rude questions.'),
    ('Pretend your coffee is your very strict boss.'),
    ('Deliver breaking news about a stolen chicken nugget.'),
    ('Teach a masterclass on dramatic eye contact with invisible pigeons.'),
    ('Narrate a cooking show where absolutely nothing is edible.'),
    ('Act like a medieval knight discovering online shopping.'),
    ('Describe an elevator ride like it changed your life forever.'),
    ('Convince your Target that spoons are plotting something.'),
    ('Pretend you are a personal trainer for couch potatoes only.'),
    ('Ask for a raise from an imaginary boss who is also a goose.'),
    ('Sell a haunted water bottle with too much enthusiasm.'),
    ('Explain why your socks deserve privacy.'),
    ('Introduce your Target like they are the grand champion of awkward timing.'),
    ('Perform a nature documentary about a wild human searching for snacks.'),
    ('Pretend your backpack is filing a complaint against you.'),
    ('React to a single raisin like it holds terrible secrets.'),
    ('Describe a public bus like it is a luxury spaceship.'),
    ('Act like you have just returned from battle with a stubborn jar lid.'),
    ('Try to start a revolution against alarm clocks.'),
    ('Explain shampoo to a very judgmental cowboy.'),
    ('Make an emotional support speech for a broken flip-flop.'),
    ('Pretend you are a pop star whose biggest hit is about soup.'),
    ('Describe your Target like they are the final contestant on a game show called Maybe.'),
    ('Ask an invisible intern to bring you courage immediately.'),
    ('Deliver a dramatic confession about eating the last cookie.'),
    ('Act like your living room is an active volcano evacuation zone.'),
    ('Pitch a startup that delivers emergency compliments.'),
    ('Explain your favorite snack like it deserves a national holiday.'),
    ('Pretend you are a vampire with terrible customer service.'),
    ('Narrate your Target taking a sip like championship footage.'),
    ('Make a royal decree banning boring small talk.'),
    ('Describe a hoodie like it is a loyal war companion.'),
    ('Act like you are hosting an awards ceremony for kitchen appliances.'),
    ('Try to impress your Target with your invisible accordion business.'),
    ('Explain why your future depends on finding one clean spoon.'),
    ('Pretend you are a therapist for emotionally unavailable sandwiches.'),
    ('Perform a villain origin story caused by stepping on wet socks.'),
    ('Describe a pillow like it owes you money.'),
    ('Act like your mirror started copying you badly.'),
    ('Explain a group chat like it is a dangerous ecosystem.'),
    ('Make a hard-boiled detective speech about missing fries.'),
    ('Pretend you are a disappointed talent judge reviewing a banana peel.'),
    ('Try to sound seductive while talking about tax forms.'),
    ('Describe your fridge as if it is keeping state secrets.'),
    ('Act like you are the captain of a ship full of toddlers and juice boxes.'),
    ('Announce a fashion line inspired by panic and laundry day.'),
    ('Explain friendship to an enemy toaster.'),
    ('Pretend your knees have separate personalities and one of them is dramatic.'),
    ('Give a guided meditation for people who just lost an argument to a toddler.'),
    ('Describe a traffic cone like it is the chosen one.'),
    ('Act like an exhausted magician whose only trick is finding chargers.'),
    ('Beg your Target to respect the sacred code of leftovers.'),
    ('Pretend you are a fashion critic reviewing pajamas at noon.'),
    ('Explain a hangover to someone who thinks it is a myth.'),
    ('Narrate an epic duel between you and a mosquito.'),
    ('Describe your phone battery like a tragic hero.'),
    ('Act like your invisible assistant keeps making everything weirder.'),
    ('Pitch a horror movie about an unread email.'),
    ('Explain cereal to a medieval peasant with confidence.'),
    ('Pretend your Target is auditioning for the role of suspicious potato.'),
    ('Make a heartfelt speech to win back your favorite mug.'),
    ('Describe an office meeting like a survival challenge.'),
    ('Act like you are a billionaire investor in premium nonsense.'),
    ('Explain why the couch has become too powerful.'),
    ('Pretend you are hosting the world championship of awkward waving.'),
    ('Narrate your own betrayal after dropping food on the floor.'),
    ('Describe a pair of flip-flops like they are elite athletes.'),
    ('Act like your neighbor just declared war with a leaf blower.'),
    ('Explain chewing gum like it belongs in a spy thriller.'),
    ('Beg an imaginary bouncer to let your confidence into the club.'),
    ('Pretend you are a dramatic lifeguard at a kiddie pool.'),
    ('Describe a nap as if it is a forbidden romance.'),
    ('Act like your Target just discovered fire and needs media training.'),
    ('Give a product demo for invisible anti-awkwardness spray.'),
    ('Explain leftovers like they are a complicated family drama.'),
    ('Pretend your shoelace is a toxic ex who keeps coming back.'),
    ('Narrate a wildlife documentary about someone avoiding eye contact.'),
    ('Describe a spoonful of soup like it is an extreme sport.'),
    ('Act like an opera singer who is furious about losing one sock.'),
    ('Explain why elevators are just emotional escape rooms.'),
    ('Pretend you are a royal butler serving one single chicken nugget.'),
    ('Describe your Target like they are the human version of a plot twist.'),
    ('Act like you have been betrayed by a suspiciously quiet microwave.'),
    ('Pitch a dating app exclusively for people who love snacks too much.'),
    ('Explain a paper towel to someone like it is cutting-edge technology.'),
    ('Pretend your invisible horse is offended by your posture.'),
    ('Make a championship call for someone successfully opening a jar.'),
    ('Describe a grocery list like it is prophecy.'),
    ('Act like your best friend is an overly dramatic ceiling fan.'),
    ('Explain why your water bottle deserves a promotion.'),
    ('Pretend your Target is being knighted for weird eye contact.'),
    ('Narrate a deeply emotional reunion with clean socks.'),
    ('Describe a checkout line like it is a battlefield.'),
    ('Act like you are a poet who can only write about toast.')
) AS prompts("text")
JOIN "Game" g ON g."code" = 'you-laugh-you-drink'
WHERE NOT EXISTS (
  SELECT 1
  FROM "Question" q
  WHERE q."gameId" = g."id"
    AND q."text" = prompts."text"
);
