INSERT INTO "Game" ("code", "name", "description", "published", "createdAt", "updatedAt")
SELECT
  'bad-people',
  'Bad People',
  'Savage anonymous voting game where the table picks who fits each prompt best.',
  true,
  NOW(),
  NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM "Game" WHERE "code" = 'bad-people'
);

INSERT INTO "Question" ("text", "gameId", "createdAt", "updatedAt")
SELECT prompts."text", g."id", NOW(), NOW()
FROM (
  VALUES
    ('Who would accidentally leak the group chat screenshots first?'),
    ('Who would be the worst alibi if you got arrested together?'),
    ('Who would absolutely flirt their way out of a speeding ticket?'),
    ('Who would survive the longest in a locked escape room?'),
    ('Who would panic first during a harmless power outage?'),
    ('Who would post the most dramatic breakup caption?'),
    ('Who would win a fight using confidence alone?'),
    ('Who would become annoyingly powerful if they got famous?'),
    ('Who would lie about reading the terms and conditions?'),
    ('Who would get kicked out of a wedding first?'),
    ('Who would thrive in a cult the fastest?'),
    ('Who would be the hardest to share a hotel room with?'),
    ('Who would absolutely fake being sick to dodge plans?'),
    ('Who would become a terrible boss with almost no warning?'),
    ('Who would spoil a surprise by trying too hard to help?'),
    ('Who would cry first during a motivational speech?'),
    ('Who would get caught stalking an ex online?'),
    ('Who would start a fake deep conversation just to avoid silence?'),
    ('Who would become a chaotic flight passenger?'),
    ('Who would get weirdly competitive at a baby shower game?'),
    ('Who would be the biggest menace with unlimited money?'),
    ('Who would absolutely send a risky text and regret it instantly?'),
    ('Who would survive longest in a haunted house before breaking?'),
    ('Who would be the most likely to lose their passport on vacation?'),
    ('Who would become everyone''s parent in a crisis?'),
    ('Who would definitely laugh during a serious meeting?'),
    ('Who would expose themselves by replying all?'),
    ('Who would date the biggest red flag and defend it?'),
    ('Who would get banned from a casino first?'),
    ('Who would most likely start gossip and call it concern?'),
    ('Who would get scammed by a fake celebrity account?'),
    ('Who would be the easiest to bribe with food?'),
    ('Who would accidentally join the wrong Zoom and stay anyway?'),
    ('Who would survive prison best just by making friends?'),
    ('Who would be the first one to sell everyone out in a movie plot?'),
    ('Who would become unbearably smug after one small win?'),
    ('Who would be the worst secret keeper after midnight?'),
    ('Who would throw the pettiest wedding?'),
    ('Who would get roasted online and still keep posting?'),
    ('Who would be the most suspicious with no evidence at all?'),
    ('Who would accidentally start a fire while cooking something basic?'),
    ('Who would get way too invested in a fake relationship rumor?'),
    ('Who would be most likely to peak during karaoke?'),
    ('Who would turn one compliment into a whole personality?'),
    ('Who would absolutely make a fake account to check on someone?'),
    ('Who would get into the most pointless argument in public?'),
    ('Who would become a conspiracy theorist after one podcast?'),
    ('Who would have the messiest notes app?'),
    ('Who would be worst at pretending they are not jealous?'),
    ('Who would cause the friend group to miss a flight?'),
    ('Who would become famous for the wrong reason?'),
    ('Who would fold first during a high-pressure lie?'),
    ('Who would most likely steal fries and deny it?'),
    ('Who would turn a small inconvenience into a life story?'),
    ('Who would get caught cheating at a game night?'),
    ('Who would become an accidental influencer?'),
    ('Who would be voted off a reality show for attitude?'),
    ('Who would most likely reconnect with an ex out of boredom?'),
    ('Who would lie confidently and almost get away with it?'),
    ('Who would absolutely send money to the wrong person?'),
    ('Who would become too powerful after one therapy session?'),
    ('Who would make the worst fake apology?'),
    ('Who would survive the apocalypse by being morally flexible?'),
    ('Who would be the most dangerous with a microphone?'),
    ('Who would most likely get married in a chaotic way?'),
    ('Who would somehow lose at hide-and-seek as an adult?'),
    ('Who would get too attached to a random stranger at a party?'),
    ('Who would definitely snoop if they found an unlocked phone?'),
    ('Who would be worst at keeping their cool under interrogation?'),
    ('Who would fake maturity the hardest?'),
    ('Who would make the group late and still act unbothered?'),
    ('Who would absolutely overreact to being left on read?'),
    ('Who would get kicked out of a group project first?'),
    ('Who would become the villain in someone''s family story?'),
    ('Who would most likely get matching tattoos without thinking?'),
    ('Who would get caught talking to themselves in public?'),
    ('Who would make an enemy at a networking event?'),
    ('Who would become fake humble after success?'),
    ('Who would most likely ruin a prank by laughing?'),
    ('Who would survive best on pure delusion and charisma?'),
    ('Who would be the hardest to trust with your spare key?'),
    ('Who would definitely get into online beef with a teenager?'),
    ('Who would be the worst person to road trip with?'),
    ('Who would absolutely become a secret hater?'),
    ('Who would throw the most passive-aggressive birthday party?'),
    ('Who would cry in the bathroom and come back like nothing happened?'),
    ('Who would be the first to become weirdly rich?'),
    ('Who would most likely marry for a story?'),
    ('Who would become unbearable after learning one new word?'),
    ('Who would panic-buy nonsense during an emergency?'),
    ('Who would get too drunk and start complimenting enemies?'),
    ('Who would be most likely to fake a dramatic exit?'),
    ('Who would make the worst person to share a secret crush with?'),
    ('Who would definitely open a text meant for someone else?'),
    ('Who would get ghosted and still send a follow-up?'),
    ('Who would become a weirdly intense gym person overnight?'),
    ('Who would be most likely to blame Mercury retrograde for everything?'),
    ('Who would survive a week without social media the worst?'),
    ('Who would be the first person to cry over a pet they just met?'),
    ('Who would absolutely join the wrong side in a family argument?'),
    ('Who would become the most annoying wedding guest?'),
    ('Who would lose their phone at the exact wrong moment?'),
    ('Who would be most likely to fake being chill about bad news?'),
    ('Who would make a terrible undercover cop?'),
    ('Who would most likely become a local legend for bad behavior?'),
    ('Who would get caught pretending to know a song lyric?'),
    ('Who would thrive in a fake-rich lifestyle?'),
    ('Who would somehow turn a parking issue into a personal feud?'),
    ('Who would absolutely get baited into posting a draft?'),
    ('Who would win an argument mostly because they are louder?'),
    ('Who would be the first to volunteer you for something awful?'),
    ('Who would become chaotic with one espresso?'),
    ('Who would definitely keep the receipt for spite?'),
    ('Who would most likely flirt with authority?'),
    ('Who would somehow make a wholesome story suspicious?'),
    ('Who would be the first person to start a revenge glow-up?'),
    ('Who would get canceled by the group chat for one opinion?'),
    ('Who would absolutely eavesdrop and pretend it was accidental?'),
    ('Who would survive longest on a reality dating show?'),
    ('Who would become weirdly loyal to a bad idea?'),
    ('Who would be most likely to borrow something and return it worse?'),
    ('Who would cry if they got publicly called out?'),
    ('Who would absolutely wear sunglasses indoors for attention?'),
    ('Who would get too emotionally attached to a vacation fling?'),
    ('Who would be most likely to start a secret second life in another city?'),
    ('Who would ruin a surprise party by asking too many questions?'),
    ('Who would make the group look suspicious at airport security?'),
    ('Who would be the easiest to frame for a harmless crime?'),
    ('Who would most likely become a manipulative game show contestant?'),
    ('Who would get into a feud with a neighbor first?'),
    ('Who would absolutely pretend they knew that all along?'),
    ('Who would be the worst at playing innocent?'),
    ('Who would turn a casual dinner into a TED Talk?'),
    ('Who would most likely become a fake minimalist?'),
    ('Who would get exposed by their own camera roll?'),
    ('Who would absolutely keep screenshots for years?'),
    ('Who would become too powerful after learning one loophole?'),
    ('Who would make the group regret giving them aux?'),
    ('Who would most likely rage-quit a board game?'),
    ('Who would be the first to take a dare too far?'),
    ('Who would absolutely show up overdressed and act casual?'),
    ('Who would most likely get catfished and keep chatting?'),
    ('Who would become the loudest person at a silent retreat?'),
    ('Who would start the worst rumor by accident?'),
    ('Who would survive a scandal with zero shame?'),
    ('Who would be the first to fake confidence before a disaster?'),
    ('Who would definitely take a free sample too seriously?'),
    ('Who would become way too powerful with a group budget?'),
    ('Who would most likely expose a fake friend fastest?'),
    ('Who would make the worst first impression on purpose?'),
    ('Who would absolutely cry over a fake scenario they invented?'),
    ('Who would get the biggest ego from a tiny bit of attention?'),
    ('Who would most likely be in the wrong and still double down?'),
    ('Who would turn a simple game into a personal mission?'),
    ('Who would most likely turn one joke into a full bit?'),
    ('Who would make the weirdest celebrity crush sound reasonable?'),
    ('Who would absolutely ask for a manager politely but intensely?'),
    ('Who would be the first to post a cryptic story after drama?'),
    ('Who would most likely weaponize silence in an argument?'),
    ('Who would become a suspiciously intense wedding planner?'),
    ('Who would most likely forget your birthday and overcompensate later?'),
    ('Who would get kicked out of an escape room for not cooperating?'),
    ('Who would absolutely download a dating app for entertainment only?'),
    ('Who would survive longest in a house full of enemies?'),
    ('Who would most likely act innocent while causing chaos?'),
    ('Who would become terrifyingly organized after one setback?'),
    ('Who would definitely ask the question everyone else was avoiding?'),
    ('Who would most likely start packing for a trip the same morning?'),
    ('Who would be the easiest to guilt-trip into helping you move?'),
    ('Who would become too honest at the worst possible time?'),
    ('Who would absolutely get caught peeking at gifts?'),
    ('Who would most likely become a villain with a good playlist?'),
    ('Who would be the first to start a fake business idea with no plan?'),
    ('Who would most likely say "I can fix them" and mean it?'),
    ('Who would get too competitive over something embarrassing?'),
    ('Who would absolutely judge everyone''s snack choices out loud?'),
    ('Who would survive best at a toxic family reunion?'),
    ('Who would most likely get blocked for being too persistent?'),
    ('Who would make the worst fake emergency excuse?'),
    ('Who would definitely get distracted during their own confession?'),
    ('Who would become weirdly powerful in a homeowners association?'),
    ('Who would most likely start a side quest in the middle of a crisis?'),
    ('Who would be the first to make a situation awkward and keep going?'),
    ('Who would absolutely show up to brunch with gossip and zero facts?'),
    ('Who would most likely become a charming scammer in another universe?'),
    ('Who would win a contest for worst timing?'),
    ('Who would most likely become impossible after one tiny promotion?'),
    ('Who would absolutely keep receipts just in case?'),
    ('Who would be the first to accidentally confess too much?'),
    ('Who would most likely get roasted and clap back too late?'),
    ('Who would become the most chaotic plus-one at an event?'),
    ('Who would definitely overthink a two-word message all day?'),
    ('Who would most likely make a fake plan just to stay home?'),
    ('Who would be the hardest to break up with cleanly?'),
    ('Who would absolutely make a dramatic toast at the wrong time?'),
    ('Who would most likely turn a hobby into a superiority complex?'),
    ('Who would become way too confident after one compliment?'),
    ('Who would definitely get exposed by their own search history?'),
    ('Who would most likely survive on audacity alone?'),
    ('Who would most likely start the drama and then ask what happened?')
) AS prompts("text")
JOIN "Game" g ON g."code" = 'bad-people'
WHERE NOT EXISTS (
  SELECT 1
  FROM "Question" q
  WHERE q."gameId" = g."id"
    AND q."text" = prompts."text"
);
