INSERT INTO "Parms" ("type", "name", "value", "createdAt")
SELECT 'EDITIONS', 'Edd''s Unconventionals', 9, NOW()
WHERE NOT EXISTS (
  SELECT 1
  FROM "Parms"
  WHERE "type" = 'EDITIONS'
    AND "name" = 'Edd''s Unconventionals'
);

INSERT INTO "Question" ("text", "gameId", "edition", "createdAt", "updatedAt")
SELECT prompts."text", g."id", edition."value", NOW(), NOW()
FROM (
  VALUES
    ('What''s a compliment that would actually hurt your feelings?', 9),
    ('What is something you achieved that didn''t feel as good as you thought it would?', 9),
    ('What''s a completely normal thing that people do that makes you irrationally angry?', 9),
    ('What''s something that you do now that your 18-year-old self would be embarrassed that you do?', 9),
    ('What''s something you''re proud of that nobody ever asks you about?', 9),
    ('What''s something you tell people you''re working on but you haven''t touched in months?', 9),
    ('What''s a pattern in your life that you can name perfectly but still haven''t broken?', 9),
    ('What''s a label that people put on you that you secretly hate?', 9),
    ('What''s something you used to judge people for but now completely understand?', 9),
    ('What is something that you know is bad for you and you know you will absolutely do again?', 9),
    ('What is the most recent moment where you acted unbothered but you were extremely bothered?', 9),
    ('What is something you have zero business being as good at as you are?', 9),
    ('What is something you have a strong opinion on that you have no experience with whatsoever?', 9),
    ('What''s a personality trait that you''re proud of that people who''ve dated you would describe completely differently?', 9),
    ('What''s something small you do in private that would genuinely confuse the people who think they know you?', 9),
    ('What is something that you thought you did for self-care but was actually self-sabotage?', 9),
    ('Is there a compliment you''ve given to someone that you immediately wanted to take back? What was it, and who was it?', 9),
    ('Which one would your Google search history prove: that you''re smart, ignorant, or slow?', 9),
    ('What''s the worst version of yourself that a specific city or person brings out?', 9),
    ('What''s the most recent compliment that made you paranoid instead of happy?', 9),
    ('What''s something you pretend not to care about because caring would make you look weak?', 9),
    ('What is a life lesson you learned way too late?', 9),
    ('What''s something you miss even though you know it was terrible for you?', 9),
    ('What do you over-explain because you''re scared of being misunderstood?', 9),
    ('What''s a red flag you ignored because the attention felt good?', 9),
    ('What''s something people praise you for that actually comes from a coping mechanism?', 9),
    ('What is a boundary you only enforce when you''re already fed up?', 9),
    ('What''s something you''ve forgiven in others that you still wouldn''t forgive in yourself?', 9),
    ('What is one lie you tell that feels harmless but probably says a lot about you?', 9),
    ('What''s something you romanticized until you actually got it?', 9),
    ('What''s a version of success that no longer impresses you?', 9),
    ('What is something you keep proving to people who are no longer watching?', 9),
    ('What''s a habit that makes your life harder but still feels comforting?', 9),
    ('What''s a conversation you''re overdue to have with yourself?', 9),
    ('What do you think people misunderstand about your confidence?', 9),
    ('What''s one thing you do when you''re jealous that you''d never admit in the moment?', 9),
    ('What''s a fear you disguise as a preference?', 9),
    ('What''s something you call standards that might actually be avoidance?', 9),
    ('What''s a warning about yourself that people should probably take more seriously?', 9),
    ('What''s something you do for closure that never actually gives you closure?', 9),
    ('What kind of disappointment hits you harder than it should?', 9),
    ('What''s a tiny rejection that stayed with you way longer than it should have?', 9),
    ('What is something you envy in people you don''t even like?', 9),
    ('What''s something you perform well emotionally but don''t actually feel?', 9),
    ('What do you think you''re over by now that you''re clearly not over?', 9),
    ('What''s something you''ve outgrown but still revisit out of habit?', 9),
    ('What''s a trait you criticize in others because you recognize it in yourself?', 9),
    ('What part of your personality only shows up when you''re deeply insecure?', 9),
    ('What''s something you thought was maturity that was really just emotional shutdown?', 9),
    ('What''s something you keep calling bad timing even though it might be avoidance?', 9),
    ('What''s the pettiest reason you''ve ever disliked someone?', 9),
    ('What''s something you want credit for even if you act like you don''t care?', 9),
    ('What is the meanest thought you''ve had about someone for no real reason?', 9),
    ('What''s something you hate being called out for because it''s usually true?', 9),
    ('What''s a version of yourself that still secretly runs your decisions?', 9),
    ('What''s something you did for love that you would never recommend to anyone else?', 9),
    ('What''s a comfort behavior that started as survival and never really left?', 9),
    ('What''s something you keep chasing that only feels good in theory?', 9),
    ('What kind of apology do you find hardest to believe?', 9),
    ('What''s something you resent people for needing from you?', 9),
    ('What''s a moment where you knew you were wrong but committed to the bit anyway?', 9),
    ('What''s a soft spot of yours that people rarely notice?', 9),
    ('What is something you fake being chill about because the alternative feels embarrassing?', 9),
    ('What''s something people assume you''re good at emotionally that you''re actually terrible at?', 9),
    ('What kind of person can still ruin your mood in seconds?', 9),
    ('What''s something you only admit to yourself when you''re alone?', 9),
    ('What''s a compliment you never believed, no matter who said it?', 9),
    ('What kind of attention do you act annoyed by but secretly enjoy?', 9),
    ('What''s a decision you defend mostly because it''s too late to undo it?', 9),
    ('What''s something you learned from a relationship you wish you had learned anywhere else?', 9),
    ('What do you do when you want distance from someone but don''t want to say it directly?', 9),
    ('What''s a situation where you were absolutely the problem but felt justified at the time?', 9),
    ('What''s something you keep calling a phase that''s clearly part of who you are?', 9),
    ('What''s a standard you expect from others that you don''t always meet yourself?', 9),
    ('What''s one thing you always notice about people immediately?', 9),
    ('What''s the strangest thing that makes you feel rejected?', 9),
    ('What''s a need you have that you struggle to say out loud?', 9),
    ('What''s something you laugh about now that genuinely wrecked you at the time?', 9),
    ('What''s a role you always end up playing in friendships whether you want to or not?', 9),
    ('What''s something you''ve made peace with that still stings a little?', 9),
    ('What is something you''re better at giving than receiving?', 9),
    ('What''s a version of honesty you only use when you''re angry?', 9),
    ('What''s something you only recognize as loneliness after the fact?', 9),
    ('What''s one thing you think people should apologize to you for that they never will?', 9),
    ('What kind of behavior makes you lose respect for someone immediately?', 9),
    ('What''s something you still take personally even though you know better?', 9),
    ('What''s a rule you made for yourself after one bad experience?', 9),
    ('What part of being understood feels uncomfortable to you?', 9),
    ('What do people assume is easy for you that actually drains you?', 9),
    ('What''s something you wish people asked you about more often?', 9),
    ('What''s one thing you secretly want to be chosen for?', 9),
    ('What''s an insecurity that shows up as control?', 9),
    ('What''s something you never post because it feels too revealing?', 9),
    ('What kind of person brings out your most immature side?', 9),
    ('What''s a mistake you keep making in slightly different outfits?', 9),
    ('What is something you find hard to celebrate in yourself without downplaying it?', 9),
    ('What''s a truth about your life that sounds dramatic but is accurate?', 9),
    ('What''s something you don''t regret, but definitely wouldn''t do again?', 9),
    ('What''s an emotional risk you act above but are actually terrified of?', 9),
    ('What''s something you keep expecting from people who have already shown you they can''t give it?', 9),
    ('What''s a part of your personality that only comes out when you feel safe?', 9),
    ('What''s something you learned to laugh off because explaining the hurt took too much energy?', 9),
    ('What kind of silence makes you spiral the fastest?', 9),
    ('What''s one way you sabotage good things before they get the chance to disappoint you?', 9),
    ('What do you cling to long after it has stopped being kind to you?', 9),
    ('What''s a compliment you wanted from one specific person and never got?', 9),
    ('What''s something you inherited emotionally that you''re still trying to unlearn?', 9),
    ('What''s the difference between how people see you and how you experience yourself?', 9),
    ('What''s a choice you made out of fear that changed your life more than you''d like to admit?', 9),
    ('What''s something you call independence that might actually be isolation?', 9),
    ('What''s a promise you keep making to yourself and breaking quietly?', 9),
    ('What''s something you''re oddly defensive about even though no one is attacking you?', 9),
    ('What''s one memory you revisit when you need proof that you mattered to someone?', 9),
    ('What''s something you made fun of until you needed it yourself?', 9),
    ('What''s a form of validation you know you shouldn''t need but still crave?', 9),
    ('What''s a type of person you attract when you''re not doing well?', 9),
    ('What''s something you miss about a version of yourself you don''t want back?', 9),
    ('What''s a situation where your pride cost you something real?', 9),
    ('What''s the kindest thing you''ve done for someone while secretly resenting it?', 9),
    ('What''s one thing you hope people never notice about the way you cope?', 9),
    ('What''s a moment you looked composed on the outside and fell apart later?', 9),
    ('What''s something you protect in yourself like it''s fragile glass?', 9),
    ('What''s a standard you created to avoid ever feeling foolish again?', 9),
    ('What''s a way you punish yourself that doesn''t look like punishment from the outside?', 9),
    ('What kind of affection makes you suspicious instead of comforted?', 9),
    ('What''s a part of adulthood you still feel emotionally unprepared for?', 9),
    ('What''s one thing people rely on you for that you''re tired of providing?', 9),
    ('What''s something you had to lose before you understood its value?', 9),
    ('What''s a version of yourself you perform at work, online, or in public?', 9),
    ('What''s one thing you wish people noticed without you having to ask?', 9),
    ('What''s something that bruises your ego faster than it should?', 9),
    ('What''s a dynamic you know is unhealthy but still understand too well?', 9),
    ('What''s a piece of advice you give others but avoid taking yourself?', 9),
    ('What do you think your younger self would be relieved to know about you now?', 9),
    ('What''s something you resent being good at because people now expect it from you?', 9),
    ('What''s a kind of confrontation that makes you instantly shut down?', 9),
    ('What''s one thing you pretend is no big deal because you don''t want to seem needy?', 9),
    ('What''s a role model disappointment that changed how you trust people?', 9),
    ('What''s something you turned into a joke so no one would realize it mattered?', 9),
    ('What''s an insecurity you disguise as being selective?', 9),
    ('What''s a sacrifice you made that nobody fully appreciated?', 9),
    ('What''s something you keep trying to earn that should probably be given freely?', 9),
    ('What''s one thing you''re still waiting to hear from someone who has moved on?', 9),
    ('What''s a version of closure you''ve had to create for yourself?', 9),
    ('What''s something you judged yourself for while everyone else gave you grace?', 9),
    ('What''s a skill you developed because you had to read the room early?', 9),
    ('What''s a kind of chaos that feels strangely familiar to you?', 9),
    ('What''s one thing you keep private because once it''s spoken, it becomes too real?', 9),
    ('What''s a place, song, or smell that immediately changes your emotional weather?', 9),
    ('What''s something you confuse with love because it used to mean safety?', 9),
    ('What''s an argument you''ve replayed so often that you''ve rewritten it in your head?', 9),
    ('What''s one thing you know about yourself now that would have scared the old you?', 9),
    ('What''s a way you know you''re overwhelmed before you admit it out loud?', 9),
    ('What''s something you said you were okay with and definitely weren''t?', 9),
    ('What''s a trait you admire in others but have a hard time accepting in yourself?', 9),
    ('What''s a pattern you mistake for chemistry?', 9),
    ('What''s something you do when you want reassurance without asking for reassurance?', 9),
    ('What''s the smallest act of kindness you''ve never forgotten?', 9),
    ('What''s one thing you keep almost saying and then decide not to?', 9),
    ('What''s a fear that shows up most when things are finally going well?', 9),
    ('What''s something you romanticize only because you never had enough of it?', 9),
    ('What''s a place in your life where you''ve confused loyalty with self-abandonment?', 9),
    ('What''s one thing you keep returning to even though you know exactly how it ends?', 9),
    ('What''s a reaction from someone that can still make you feel twelve years old?', 9),
    ('What''s a hard truth that got easier only after it got embarrassing?', 9),
    ('What''s something you''ve made peace with intellectually but not emotionally?', 9),
    ('What''s a behavior from other people that instantly makes you guard yourself?', 9),
    ('What''s one thing you''d change about how you ask for help?', 9),
    ('What''s a soft habit of yours that actually means you''re not okay?', 9),
    ('What''s something you want to be admired for but rarely let people see?', 9),
    ('What''s a compliment that sounds nice but lands like pressure?', 9),
    ('What''s one thing you do when you''re trying not to look hurt?', 9),
    ('What''s an area of your life where you''ve confused progress with distraction?', 9),
    ('What''s a kind of person you stop being around when you''re genuinely happy?', 9),
    ('What''s something you secretly hope people notice when you go quiet?', 9),
    ('What''s one thing you wish you had handled worse in the moment and better afterward?', 9),
    ('What''s a kind of misunderstanding that feels impossible for you to tolerate?', 9),
    ('What''s something you find difficult to forgive because it exposed your own desperation?', 9),
    ('What''s one thing you still overcompensate for from years ago?', 9),
    ('What''s a situation where you wanted honesty but only the flattering kind?', 9),
    ('What''s a belief about yourself that gets stronger when you''re tired?', 9),
    ('What''s one thing you miss about being less self-aware?', 9),
    ('What''s something you say is complicated when the truth is just uncomfortable?', 9),
    ('What''s a personal win that felt lonelier than it should have?', 9),
    ('What''s one thing you stay loyal to because leaving would force you to redefine yourself?', 9),
    ('What''s a quality in yourself that only feels valuable when someone else points it out?', 9),
    ('What''s a type of rejection you''ve gotten good at predicting?', 9),
    ('What''s something you fear becoming even though parts of it already live in you?', 9),
    ('What''s one way stress changes your personality?', 9),
    ('What''s a place in your life where you''ve accepted crumbs and called it patience?', 9),
    ('What''s something you only admit in your notes app, drafts, or unsent messages?', 9),
    ('What''s a piece of your healing that still feels ugly to witness?', 9),
    ('What''s one thing you want forgiven without ever having to explain it?', 9),
    ('What''s a kind of generosity that drains you more than it fulfills you?', 9),
    ('What''s something you avoid because being bad at it feels unbearable?', 9),
    ('What''s a fantasy about your future that says a lot about what you''re missing now?', 9),
    ('What''s one thing you treat like a flaw because someone once mocked it?', 9),
    ('What''s a recurring argument you keep having with reality?', 9),
    ('What''s something you hope your friends understand about you without you spelling it out?', 9),
    ('What''s one thing you do when you''re trying to seem unaffected?', 9),
    ('What''s a life update you dread people asking about?', 9),
    ('What''s something you still think you''d be better at if you had been loved differently?', 9),
    ('What''s one thing you learned to hide because it changed how people treated you?', 9),
    ('What''s a way you act when you''re trying not to get too attached?', 9),
    ('What''s a kindness you rejected because you didn''t trust the intention behind it?', 9),
    ('What''s something you want to be known for that your current life doesn''t show yet?', 9),
    ('What''s one rule you live by that came from a wound, not wisdom?', 9),
    ('What''s a side of yourself that appears only when you''re deeply comfortable?', 9),
    ('What''s something you keep calling random when it follows the same emotional script every time?', 9),
    ('What''s one thing you do to create distance while pretending everything is normal?', 9),
    ('What''s a compliment you struggle to accept because it raises the bar?', 9),
    ('What''s something you think you''re too old, too smart, or too healed to still be doing?', 9),
    ('What''s a hurt that only shows up when someone gets close in the right way?', 9),
    ('What''s one thing you''ve made your whole personality in certain seasons of your life?', 9),
    ('What''s something you wish people understood about your anger?', 9),
    ('What''s a decision you keep defending because admitting regret would crack something open?', 9),
    ('What''s one thing that makes you feel replaceable instantly?', 9),
    ('What''s a version of yourself you bring out to survive family spaces?', 9),
    ('What''s something you over-give because you''re scared your presence alone isn''t enough?', 9),
    ('What''s a conversation topic that makes you feel exposed no matter how casually it comes up?', 9),
    ('What''s one thing you don''t like about the person you become when you''re lonely?', 9),
    ('What''s a way you test people without telling them they''re being tested?', 9),
    ('What''s something you keep trying to prove through your work, style, body, or choices?', 9),
    ('What''s one thing you''ve survived that still doesn''t feel fully over?', 9),
    ('What''s a kind of stability you once found boring and now deeply respect?', 9),
    ('What''s something you avoided grieving by immediately turning it into a lesson?', 9),
    ('What''s one thing your instincts were right about before your logic caught up?', 9),
    ('What''s a behavior you excuse in people you want to keep around?', 9),
    ('What''s something you wish you could ask for without feeling dramatic?', 9),
    ('What''s one thing you accepted because asking for more felt too risky?', 9),
    ('What''s a version of attention that feels like care to you even when it isn''t?', 9),
    ('What''s something you outgrew emotionally before you outgrew it physically or socially?', 9),
    ('What''s one thing you keep preparing for that may never happen?', 9),
    ('What''s a personality trait people reward in you that you think might be hurting you?', 9),
    ('What''s a type of praise that makes you feel seen in the wrong way?', 9),
    ('What''s something you regret normalizing in your own life?', 9),
    ('What''s one thing you still believe about yourself on your worst days?', 9),
    ('What''s a kind of effort you stopped making because nobody seemed to notice it anyway?', 9),
    ('What''s something you keep organized because chaos there would expose more than mess?', 9),
    ('What''s one thing you''d like to tell your past self without softening the truth?', 9),
    ('What''s a tension between who you are and who people expect you to be?', 9),
    ('What''s something you looked down on until life humbled you into understanding it?', 9),
    ('What''s one thing you do when you want someone to miss you?', 9),
    ('What''s a way your humor protects you from being fully known?', 9),
    ('What''s something you deeply value that your lifestyle doesn''t fully reflect yet?', 9),
    ('What''s one thing you haven''t forgiven yourself for misunderstanding sooner?', 9),
    ('What''s a behavior you call independence that others might experience as distance?', 9),
    ('What''s something that instantly makes you feel emotionally homeless?', 9),
    ('What''s one thing you wish someone had taught you about love before you improvised your way through it?', 9),
    ('What''s a goal you chased mostly because it looked like proof?', 9),
    ('What''s something you keep private because you don''t want advice, just witness?', 9),
    ('What''s one thing that makes your chest tighten before your brain understands why?', 9),
    ('What''s a version of failure you''re still trying not to repeat?', 9),
    ('What''s something you can forgive in strangers but not in people you love?', 9),
    ('What''s one thing you do when you''re trying not to need anybody?', 9),
    ('What''s a dream you''ve quietly downgraded so it would hurt less if it never happened?', 9),
    ('What''s something you keep polished on the outside because the inside feels messier?', 9),
    ('What''s one thing you romanticize because it would excuse your current restlessness?', 9),
    ('What''s a kind of honesty you appreciate in theory and hate in practice?', 9),
    ('What''s something you used to think was weakness that now feels emotionally advanced?', 9),
    ('What''s one thing that made you realize you were lonelier than you thought?', 9),
    ('What''s a boundary you set only after you let too much slide?', 9),
    ('What''s something you keep waiting to enjoy once you''ve earned it enough?', 9),
    ('What''s one thing you''re scared people only tolerate about you instead of loving?', 9),
    ('What''s a piece of your identity that feels harder to carry in some rooms than others?', 9),
    ('What''s something you feel guilty for wanting more of?', 9),
    ('What''s one way your body tells the truth before your mouth does?', 9),
    ('What''s a situation where you confused being wanted with being valued?', 9),
    ('What''s something you''ve become really good at because you never felt safe being bad at it?', 9),
    ('What''s one thing you pretend is temporary because making it permanent would force a bigger decision?', 9),
    ('What''s a quality in other people that makes you feel instantly softer?', 9),
    ('What''s something you keep comparing your life to even though you know the comparison is unfair?', 9),
    ('What''s one thing you''d stop doing if you truly believed you were enough already?', 9),
    ('What''s a feeling you only know how to process by moving, cleaning, scrolling, or disappearing?', 9),
    ('What''s something you think would break your heart more now than it would have before?', 9),
    ('What''s one thing you''ve had to teach yourself because no one around you modeled it well?', 9),
    ('What''s a kind of loss that doesn''t sound dramatic until you live through it?', 9),
    ('What''s something you keep making jokes about because the real version is still tender?', 9),
    ('What''s one thing people think is natural for you that is actually carefully managed?', 9),
    ('What''s a moment where you realized you were asking for too little?', 9),
    ('What''s something you say you''re over because admitting hope would feel riskier?', 9),
    ('What''s one thing you admire in people who are emotionally uncomplicated?', 9),
    ('What''s a way you make yourself smaller in rooms where you don''t feel secure?', 9),
    ('What''s something you miss from a chapter of life you would never actually return to?', 9),
    ('What''s one thing you wish people believed the first time you said it?', 9),
    ('What''s a lie you tell yourself when you want to avoid making a change?', 9),
    ('What''s something you''ve mistaken for intuition that was really fear wearing a smarter outfit?', 9),
    ('What''s one thing you keep doing because it protects you from embarrassment more than harm?', 9),
    ('What''s a version of intimacy that still feels unfamiliar even when you want it?', 9),
    ('What''s something you want to unlearn before it starts shaping the rest of your life?', 9),
    ('What''s one thing you hope the people who hurt you never get to feel too certain about?', 9),
    ('What''s a kind of grief that sneaks up on you when life finally gets quiet?', 9),
    ('What''s something you''ve had to relearn because survival taught you the opposite?', 9),
    ('What''s one thing you want to be brave about before this year ends?', 9),
    ('What''s something you still need permission to stop carrying?', 9),
    ('What''s a part of your life that looks settled from the outside but doesn''t feel settled to you?', 9),
    ('What''s one thing you wish you could believe about yourself without needing evidence first?', 9),
    ('What''s a kind of tenderness you still don''t fully know how to receive?', 9),
    ('What''s something you keep postponing because doing it would confirm how much it matters?', 9),
    ('What''s one truth about your current season of life that you''re only just beginning to accept?', 9)
) AS prompts("text", "edition")
JOIN "Game" g ON g."code" = 'truth-or-drink'
JOIN "Parms" edition
  ON edition."type" = 'EDITIONS'
 AND edition."name" = 'Edd''s Unconventionals'
WHERE NOT EXISTS (
  SELECT 1
  FROM "Question" q
  WHERE q."gameId" = g."id"
    AND q."edition" = edition."value"
    AND q."text" = prompts."text"
);
