INSERT INTO "Game" ("code", "name", "description", "published", "createdAt", "updatedAt")
SELECT
  'name-the-song',
  'Name The Song',
  'See a song title with the vowels removed, buzz first, answer in 30 seconds, then score the round as correct or wrong.',
  true,
  NOW(),
  NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM "Game" WHERE "code" = 'name-the-song'
);

INSERT INTO "Question" ("text", "gameId", "createdAt", "updatedAt")
SELECT songs."text", g."id", NOW(), NOW()
FROM (
  VALUES
    ('Bohemian Rhapsody|Queen'),
    ('Shape of You|Ed Sheeran'),
    ('Blinding Lights|The Weeknd'),
    ('Uptown Funk|Mark Ronson ft. Bruno Mars'),
    ('Rolling in the Deep|Adele'),
    ('Someone Like You|Adele'),
    ('Shake It Off|Taylor Swift'),
    ('Bad Guy|Billie Eilish'),
    ('Billie Jean|Michael Jackson'),
    ('Thriller|Michael Jackson'),
    ('Smooth Criminal|Michael Jackson'),
    ('Beat It|Michael Jackson'),
    ('Don''t Stop Believin''|Journey'),
    ('Sweet Child O'' Mine|Guns N'' Roses'),
    ('Livin'' on a Prayer|Bon Jovi'),
    ('Wonderwall|Oasis'),
    ('Mr. Brightside|The Killers'),
    ('Hey Jude|The Beatles'),
    ('Let It Be|The Beatles'),
    ('Yesterday|The Beatles'),
    ('Imagine|John Lennon'),
    ('Hotel California|Eagles'),
    ('Smells Like Teen Spirit|Nirvana'),
    ('Lose Yourself|Eminem'),
    ('Without Me|Eminem'),
    ('Numb|Linkin Park'),
    ('In the End|Linkin Park'),
    ('Hips Don''t Lie|Shakira ft. Wyclef Jean'),
    ('Waka Waka|Shakira'),
    ('Despacito|Luis Fonsi ft. Daddy Yankee'),
    ('Bailando|Enrique Iglesias'),
    ('Gasolina|Daddy Yankee'),
    ('Havana|Camila Cabello'),
    ('Senorita|Shawn Mendes and Camila Cabello'),
    ('Perfect|Ed Sheeran'),
    ('Thinking Out Loud|Ed Sheeran'),
    ('Photograph|Ed Sheeran'),
    ('All of Me|John Legend'),
    ('Stay With Me|Sam Smith'),
    ('Hello|Adele'),
    ('Set Fire to the Rain|Adele'),
    ('Chandelier|Sia'),
    ('Cheap Thrills|Sia'),
    ('Roar|Katy Perry'),
    ('Firework|Katy Perry'),
    ('Teenage Dream|Katy Perry'),
    ('California Gurls|Katy Perry'),
    ('Dark Horse|Katy Perry'),
    ('Last Friday Night|Katy Perry'),
    ('Poker Face|Lady Gaga'),
    ('Bad Romance|Lady Gaga'),
    ('Born This Way|Lady Gaga'),
    ('Shallow|Lady Gaga and Bradley Cooper'),
    ('Flowers|Miley Cyrus'),
    ('Wrecking Ball|Miley Cyrus'),
    ('Party in the U.S.A.|Miley Cyrus'),
    ('Can''t Stop the Feeling!|Justin Timberlake'),
    ('Sorry|Justin Bieber'),
    ('Love Yourself|Justin Bieber'),
    ('Baby|Justin Bieber'),
    ('Peaches|Justin Bieber'),
    ('Stay|The Kid LAROI and Justin Bieber'),
    ('Levitating|Dua Lipa'),
    ('Dance Monkey|Tones and I'),
    ('Closer|The Chainsmokers ft. Halsey'),
    ('Rockstar|Post Malone ft. 21 Savage'),
    ('Sunflower|Post Malone and Swae Lee'),
    ('Circles|Post Malone'),
    ('Old Town Road|Lil Nas X'),
    ('Industry Baby|Lil Nas X and Jack Harlow'),
    ('We Will Rock You|Queen'),
    ('We Are the Champions|Queen'),
    ('Another One Bites the Dust|Queen'),
    ('Radio Ga Ga|Queen'),
    ('I Want It That Way|Backstreet Boys'),
    ('Everybody|Backstreet Boys'),
    ('Bye Bye Bye|NSYNC'),
    ('Toxic|Britney Spears'),
    ('...Baby One More Time|Britney Spears'),
    ('Oops!... I Did It Again|Britney Spears'),
    ('Genie in a Bottle|Christina Aguilera'),
    ('Beautiful|Christina Aguilera'),
    ('Umbrella|Rihanna ft. Jay-Z'),
    ('Diamonds|Rihanna'),
    ('We Found Love|Rihanna ft. Calvin Harris'),
    ('Only Girl|Rihanna'),
    ('Pon de Replay|Rihanna'),
    ('Single Ladies|Beyonce'),
    ('Halo|Beyonce'),
    ('Crazy in Love|Beyonce ft. Jay-Z'),
    ('Irreplaceable|Beyonce'),
    ('Formation|Beyonce'),
    ('Empire State of Mind|Jay-Z ft. Alicia Keys'),
    ('Stronger|Kanye West'),
    ('Gold Digger|Kanye West ft. Jamie Foxx'),
    ('Heartless|Kanye West'),
    ('Good 4 U|Olivia Rodrigo'),
    ('Drivers License|Olivia Rodrigo'),
    ('Vampire|Olivia Rodrigo'),
    ('Anti-Hero|Taylor Swift'),
    ('Call Me Maybe|Carly Rae Jepsen'),
    ('Royals|Lorde'),
    ('Happy|Pharrell Williams'),
    ('Get Lucky|Daft Punk ft. Pharrell Williams'),
    ('Locked Out of Heaven|Bruno Mars'),
    ('Grenade|Bruno Mars'),
    ('Just the Way You Are|Bruno Mars'),
    ('That''s What I Like|Bruno Mars'),
    ('24K Magic|Bruno Mars'),
    ('Treasure|Bruno Mars'),
    ('Run the World (Girls)|Beyonce'),
    ('Drunk in Love|Beyonce ft. Jay-Z'),
    ('Work|Rihanna ft. Drake'),
    ('Needed Me|Rihanna'),
    ('Love on the Brain|Rihanna'),
    ('S and M|Rihanna'),
    ('Rude Boy|Rihanna'),
    ('What Makes You Beautiful|One Direction'),
    ('Story of My Life|One Direction'),
    ('Drag Me Down|One Direction'),
    ('Best Song Ever|One Direction'),
    ('Steal My Girl|One Direction'),
    ('Night Changes|One Direction'),
    ('What Do You Mean?|Justin Bieber'),
    ('Purpose|Justin Bieber'),
    ('Boyfriend|Justin Bieber'),
    ('Beauty and a Beat|Justin Bieber ft. Nicki Minaj'),
    ('Starships|Nicki Minaj'),
    ('Super Bass|Nicki Minaj'),
    ('Anaconda|Nicki Minaj'),
    ('Bang Bang|Jessie J, Ariana Grande and Nicki Minaj'),
    ('Problem|Ariana Grande ft. Iggy Azalea'),
    ('Thank U, Next|Ariana Grande'),
    ('7 Rings|Ariana Grande'),
    ('No Tears Left to Cry|Ariana Grande'),
    ('Into You|Ariana Grande'),
    ('Dangerous Woman|Ariana Grande'),
    ('The Hills|The Weeknd'),
    ('Starboy|The Weeknd ft. Daft Punk'),
    ('Can''t Feel My Face|The Weeknd'),
    ('Earned It|The Weeknd'),
    ('I Feel It Coming|The Weeknd ft. Daft Punk'),
    ('One Dance|Drake'),
    ('God''s Plan|Drake'),
    ('Hotline Bling|Drake'),
    ('In My Feelings|Drake'),
    ('Started From the Bottom|Drake'),
    ('Take Care|Drake ft. Rihanna'),
    ('Someone You Loved|Lewis Capaldi'),
    ('Wake Me Up|Avicii'),
    ('Levels|Avicii'),
    ('Hey Brother|Avicii'),
    ('The Nights|Avicii'),
    ('Titanium|David Guetta ft. Sia'),
    ('Without You|David Guetta ft. Usher'),
    ('Turn Me On|David Guetta ft. Nicki Minaj'),
    ('Where Them Girls At|David Guetta ft. Flo Rida and Nicki Minaj'),
    ('We Are Young|fun. ft. Janelle Monae'),
    ('Some Nights|fun.'),
    ('Counting Stars|OneRepublic'),
    ('Love Me Like You Do|Ellie Goulding'),
    ('Secrets|OneRepublic'),
    ('Pompeii|Bastille'),
    ('Radioactive|Imagine Dragons'),
    ('Demons|Imagine Dragons'),
    ('Believer|Imagine Dragons'),
    ('Thunder|Imagine Dragons'),
    ('On Top of the World|Imagine Dragons'),
    ('Whatever It Takes|Imagine Dragons'),
    ('A Sky Full of Stars|Coldplay'),
    ('Paradise|Coldplay'),
    ('Adventure of a Lifetime|Coldplay'),
    ('Something Just Like This|The Chainsmokers and Coldplay'),
    ('Closer to the Edge|30 Seconds to Mars'),
    ('Stitches|Shawn Mendes'),
    ('Good Time|Owl City and Carly Rae Jepsen'),
    ('Stronger (What Doesn''t Kill You)|Kelly Clarkson'),
    ('Sugar|Maroon 5'),
    ('Jar of Hearts|Christina Perri'),
    ('A Thousand Years|Christina Perri'),
    ('All About That Bass|Meghan Trainor'),
    ('Lips Are Movin|Meghan Trainor'),
    ('Memories|Maroon 5'),
    ('Shut Up and Dance|Walk the Moon'),
    ('Riptide|Vance Joy'),
    ('Take Me to Church|Hozier'),
    ('Budapest|George Ezra'),
    ('Ho Hey|The Lumineers'),
    ('Little Talks|Of Monsters and Men'),
    ('Cool Kids|Echosmith'),
    ('Sweater Weather|The Neighbourhood'),
    ('Black Beatles|Rae Sremmurd ft. Gucci Mane'),
    ('Trap Queen|Fetty Wap'),
    ('679|Fetty Wap ft. Remy Boyz'),
    ('Fight Song|Rachel Platten'),
    ('Elastic Heart|Sia'),
    ('Habits (Stay High)|Tove Lo'),
    ('Team|Lorde'),
    ('Latch|Disclosure ft. Sam Smith'),
    ('Rather Be|Clean Bandit ft. Jess Glynne')
) AS songs("text")
JOIN "Game" g ON g."code" = 'name-the-song'
WHERE NOT EXISTS (
  SELECT 1
  FROM "Question" q
  WHERE q."gameId" = g."id"
    AND q."text" = songs."text"
);
